version: '3.8'

services:
  crypto_service:
    build:
      context: ./crypto_service
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    volumes:
      - ./crypto_service:/crypto_service
    networks:
      - trading_web3_network
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/backend_db
    ports:
      - 8080:8080
    volumes:
      - ./backend:/backend
    networks:
      - trading_web3_network
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend_db
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - trading_web3_network

networks:
  trading_web3_network:
    driver: bridge